activity/urls.py
from django.urls import path

from . import views


app_name = "activity"

urlpatterns = [
    path("", views.home, name="home"),
    path("update_activity/<int:id>/", views.update_activity, name="update_activity"),
    path("delete_activity/<int:id>/", views.delete_activity, name="delete_activity"),
]

book/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = "book"

urlpatterns = [
    path("", views.home, name="home"),
    path("books/", views.books, name="books"),
    path("books/<int:id>/", views.open_book, name="open_book"),
    path("delete_book/<int:id>/", views.delete_book, name="delete_book"),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("dashboard.urls")),
    path("note/", include("note.urls")),
    path("homework/", include("homework.urls")),
    path("youtube/", include("youtube.urls")),
    path("activity/", include("activity.urls")),
    path("book/", include("book.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("wiki/", include("wiki.urls")),
    path("conversion/", include("conversion.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

activity/models.py
from django.db import models
from django.contrib.auth.models import User


"""
Activity model with fields:
1. user
2. title
3. is_finished
"""
class Activity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        """
        return the titile of the activity
        """
        return self.title

activity/forms.py
from django import forms

from .models import Activity


"""
model form to create an activity
fields - title
"""
class ActivityForm(forms.ModelForm):
    """define the model, fields, labels and widgets"""
    title = forms.CharField(max_length=200, label="", required=True, widget=forms.widgets.TextInput(attrs={"class": "form-control", "placeholder" : "Activity Title"}))
    class Meta:
        model = Activity
        fields = ["title"]
        

activity/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Activity
from .forms import ActivityForm


@login_required
def home(request):
    """
    display all activities(title, status, delete action)
    show an add activity form
    """
    if request.method == "POST":
        form = ActivityForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data.get("title")
            
            activity = Activity(user=request.user, title=title)
            activity.save()
            messages.success(request, f"Activity '{title.upper()}' added.")

            return redirect("activity:home")

    else:
        form = ActivityForm()

    activities = Activity.objects.filter(user=request.user)

    return render(request, "activity/home.html", {
        "title": "activities",
        "activities": activities,
        "form": form
    })


@login_required
def update_activity(request, id):
    """
    update the status of the activity from either
    is_finished or not and vice-versa
    """
    activity = Activity.objects.get(user=request.user, id=id)

    if activity.is_finished == False:
        activity.is_finished = True
        activity.save()
        messages.info(request, f"Status for activity '{activity.title.upper()}' updated")
    else:
        activity.is_finished = False
        activity.save()
        messages.info(request, f"Status for activity '{activity.title.upper()}' updated")
    return redirect("activity:home")


@login_required
def delete_activity(request, id):
    """delete a given activity"""
    activity = Activity.objects.get(user=request.user, id=id)

    title = activity.title
    activity.delete()
    messages.info(request, f"Activity '{title.upper()}' deleted")

    return redirect("activity:home")
    

activity/templates/activity/home.html
{% extends 'dashboard/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    
    <!-- display activities -->
    {% if activities %}
        <div class="container-md mt-5">
            <div class="table-responsive">
                <table class="table table-sm table-striped table-hover table-dark table-bordered">
                    <caption>List of activities</caption>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for activity in activities %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td class="text-capitalize">{{ activity.title }}</td>
                                <td>
                                    <a class="text-decoration-none" href="{% url 'activity:update_activity' activity.id %}">
                                        <div class="text-light">
                                            {% if activity.is_finished == True %}
                                                <input class="form-cntrol" type="checkbox" name="" id="" checked>
                                            {% else %}
                                                <input class="form-cntrol" type="checkbox" name="" id="">
                                            {% endif %}
                                            &nbsp;
                                            Mark as complete   
                                        </div>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'activity:delete_activity' activity.id %}">
                                        <i class="fa-solid fa-trash fa-lg"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %} 
        <h3 class="alert alert-info mt-3">No activities listed so far</h3> 
    {% endif %}


    <!-- create activity form -->
    <div class="container mt-5" style="margin-bottom: 120px;">
        <div class="card">
            <fieldset>
                <legend class="card-title text-center text-primary mt-3">
                    <h2 class="fw-bold fs-2">Add an activity</h2>
                </legend>
            </fieldset>
            <form class="form-group" action="" method="post" autocomplete="off">
                {% csrf_token %}
                <fieldset class="card-body">
                    {{ form|crispy }}
                </fieldset>
                <fieldest class="card-footer mt-auto">
                    <button class="btn btn-info text-center" type="submit">
                        Add
                    </button>
                </fieldest>
            </form>
        </div>
    </div>
        
{% endblock content %}
    