activity/urls.py
from django.urls import path

from . import views


app_name = "activity"

urlpatterns = [
    path("", views.home, name="home"),
    path("update_activity/<int:id>/", views.update_activity, name="update_activity"),
    path("delete_activity/<int:id>/", views.delete_activity, name="delete_activity"),
]

book/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = "book"

urlpatterns = [
    path("", views.home, name="home"),
    path("books/", views.books, name="books"),
    path("books/<int:id>/", views.open_book, name="open_book"),
    path("delete_book/<int:id>/", views.delete_book, name="delete_book"),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views


app_name = "dashboard"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register, name="register"),
    
    path("profile/", views.profile, name="profile"),
    path("signout/", views.signout, name="signout")
]

note/urls.py
from django.urls import path

from . import views


app_name = "note"

urlpatterns = [
    path("", views.home, name="home"),
    path("note-detail/<int:id>/", views.note_detail, name="note_detail"),
    path("note-delete/<int:id>/", views.note_delete, name="note_delete"),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("dashboard.urls")),
    path("note/", include("note.urls")),
    path("homework/", include("homework.urls")),
    path("youtube/", include("youtube.urls")),
    path("activity/", include("activity.urls")),
    path("book/", include("book.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("wiki/", include("wiki.urls")),
    path("conversion/", include("conversion.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wiki/urls.py
from django.urls import path

from . import views


app_name = "wiki"

urlpatterns = [
    path("", views.home, name="home"),
]

youtube/urls.py
from django.urls import path

from . import views


app_name = "youtube"

urlpatterns = [
    path("", views.home, name="home"),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        
class ChangeUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]
        

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from activity.models import Activity
from homework.models import Homework

from .forms import RegisterUserForm, ChangeUserForm


def home(request):

    return render(request, "dashboard/home.html", {"title": "dashboard"})

def login_user(request):
    if request.method == "POST":
        data = request.POST
        username = data["username"]
        password = data["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, "Logged in...")
            return redirect("dashboard:home")
            
        else:
            messages.warning(request, "Invalid details...")
            return redirect(request.path)
    
    return render(request, "dashboard/login.html", {"title": "login"})

def register(request):
    if request.user.is_authenticated:
        return redirect("dashboard:home")
    form = RegisterUserForm()
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            data = form.cleaned_data
            username = data["username"]
            password = data["password1"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, "User created and logged in...")
                return redirect("dashboard:home")
        else:
            for error in list(form.errors.value()):
                messages.warning(request, error)
            return redirect(request.path)
    
    context = {
        "title": "register",
        "form": form,
    }
    
    return render(request, "dashboard/register.html", context)

@login_required
def profile(request):
    """
    return undone activities
    return undone homeworks
    """
    activities = Activity.objects.filter(user=request.user, is_finished=False)
    homeworks = Homework.objects.filter(user=request.user, is_finished=False)

    return render(request, "dashboard/profile.html", {
        "activities": activities,
        "homeworks": homeworks,
        "title": "profile"
    })

@login_required
def signout(request):
    """
    logout the current user
    """
    logout(request)

    return redirect("dashboard:home")

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="{% static 'icon.svg' %}" type="image/x-icon">
   
    <!-- link css -->
    <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/home_style.css' %}">

    <!-- fontawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
   
    
    {% block extra_css %}
        
    {% endblock extra_css %}
        
    
    <title>
        {% if title %}
            {{ title }}
        {% endif %}   
    </title>
</head>
<body>
    {% include 'navbar.html' %}


    
    {% if messages %}
        
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
           {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
            
    {% endif %}
        

    {% block content %}
        
    {% endblock content %}
        

    <div class="footer-wrapper mt-auto">
        <footer class="bg-dark text-center text-light py-3">
            <p class="mb-0"><strong>Copyright &copy; {% now "Y" %} Alex Njuguna Kinuthia</strong></p>
        </footer>
    </div>


    
    {% block extra_js %}
        
    {% endblock extra_js %}
        


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}

{% load static %}
    

{% block content %}

<style>
    .card {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .card:hover {
        transform: scale(1.05);
        box-shadow: 8px 8px 15px rgba(0, 0, 0, 0.5);
    }

    .card:hover .card-body{
        font-weight: 500;
        letter-spacing: 2px;
        color: rgb(255, 0, 34);
    }
</style>

<div class="container-sm mt-5" style="margin-bottom: 120px;">
    <h2 class="text-center text-primary m-4">Welcome</h2>
    <hr class="mb-3">
    <div class="row">

    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'note:home' %}">
            <div class="card m-3 shadow">
                <img class="image-fluid card-header" src="{% static 'dashboard/images/notes.jpg' %}" alt="Notes"
                    style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                <h4 class="card-body text-center">Notes</h4>
                <div class="card-footer">
                    <p class="text-center">Create notes to refer to them later</p>
                </div>
            </div>
        </a>
    </div>

    
    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'homework:home' %}">
            <div class="card m-3 shadow">
                <div>
                    <img class="image-fluid card-header" src="{% static 'dashboard/images/homework.jpg' %}" alt="Homework"
                        style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <h4 class="card-body text-center">Homework</h4>
                    <p class="card-footer text-center">Add homeworks and assign them deadlines</p>
                </div>
            </div>
        </a>
    </div>
    
    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'youtube:home' %}">
            <div class="card m-3 shadow">
                <div>
                    <img class="image-fluid card-header" src="{% static 'dashboard/images/youtube.jpg' %}" alt="Youtube"
                        style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <h4 class="card-body text-center">Youtube</h4>
                    <p class="card-footer text-center">Search and play Youtube videos/tutorials</p>
                </div>
            </div>
        </a>
    </div>
    
    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'activity:home' %}">
            <div class="card m-3 shadow">
                <div>
                    <img class="image-fluid card-header" src="{% static 'dashboard/images/todo.jpg' %}" alt="To do"
                        style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <h4 class="card-body text-center">Activities</h4>
                    <p class="card-footer text-center">Add a todo list and delete them as you finish</p>
                </div>
            </div>
        </a>
    </div>
    
    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'book:home' %}">
            <div class="card m-3 shadow">
                <div>
                    <img class="image-fluid card-header" src="{% static 'dashboard/images/books.jpg' %}" alt="Books"
                        style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <h4 class="card-body text-center">Books</h4>
                    <p class="card-footer text-center">Browse books or save books for later referencing</p>
                </div>
            </div>
        </a>
    </div>
    
    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'dictionary:home' %}">
            <div class="card m-3 shadow">
                <div>
                    <img class="image-fluid card-header" src="{% static 'dashboard/images/dictionary.jpg' %}"
                        alt="Dictionary"
                        style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <h4 class="card-body text-center">Dictionary</h4>
                    <p class="card-footer text-center">Search word meanings and pronunciation</p>
                </div>
            </div>
        </a>
    </div>
    
    <div class="col-md-3">
        <a class="text-decoration-none" href="{% url 'wiki:home' %}">
            <div class="card m-3 shadow">
                <div>
                    <img class="image-fluid card-header" src="{% static 'dashboard/images/wikipedia.jpg' %}"
                        alt="Wikipedia"
                        style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius: 10px; border-top-right-radius: 10px;">
                    <h4 class="card-body text-center">Wikipedia</h4>
                    <p class="card-footer text-center">Browse information from Wikipedia</p>
                </div>
            </div>
        </a>
    </div>
   


        <div class="col-md-3">
            <a class="text-decoration-none" href="{% url 'conversion:index' %}">
                <div class="card m-3 shadow">
                        <div>
                            <img class="image-fluid card-header" src="{% static 'dashboard/images/conversion.jpg' %}" alt="notes"
                                style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius:10px; border-top-right-radius:10px;">
                                <h4 class="card-body text-center">Conversion</h4>
                                <p class="card-footer text-center">Convert weight and length to different standard units</p>
                        </div>
                </div>
            </a>
        </div>
    </div>
</div>

{% endblock content %}

    
    

dashboard/templates/dashboard/login.html
{% extends 'dashboard/base.html' %}


{% block content %}
    
    {% if user.is_authenticated %}
        <h3 class="alert alert-info">You are already logged in</h3>
    {% else %}
    <div class="container d-flex flex-column align-items-center my-5 pt-4">
        <div class="d-flex flex-column align-items-center">
            <h3 class="my-4">Login</h3>
        <form action="{% url 'dashboard:login' %}" method="post" class="form-control p-3">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" name="username" id="" class="form-control" placeholder="Username">
            </div>
            <div class="mb-3">
                <input type="password" name="password" id="" class="form-control" placeholder="password">
            </div>

            <button type="submit" class="btn btn-danger">Login</button>
        </form>

        <div class="my-3">
            <small class="text-muted fst-italic">Don't have an account? <a class="text-decoration-none text-danger" href="{% url 'dashboard:register' %}">Create</a></small>
        </div>

        </div>
        
    </div>
    {% endif %}
        
   
    
{% endblock content %}

    

dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}


{% block content %}
    <!-- display activities -->
    <div class="container-md w-75">
        {% if activities %}
        <div class="container-md mt-5">
            <div class="table-responsive">
                <table class="table table-sm table-striped table-hover table-dark table-bordered">
                    <caption>List of undone activities</caption>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
        
                    <tbody>
                        {% for activity in activities %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td class="text-capitalize">{{ activity.title }}</td>
                            <td>
                                <div class="text-light fw-bold">
                                    NOT DONE
                                </div>
                            </td>
                            <td>
                                <a href="{% url 'activity:delete_activity' activity.id %}">
                                    <i class="fa-solid fa-trash fa-lg"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% else %}
        <h3 class="alert alert-info mt-3">All activities appear done</h3>
        {% endif %}
        
        <div class="text-center">
            <a class="btn btn-primary text-center fw-bold p-2" href="{% url 'activity:home' %}">
                Activities
            </a>
        </div>
        
        
        
        
        <!-- display activities -->
        {% if homeworks %}
        <div class="container-md mt-5">
            <div class="table-responsive">
                <table class="table table-sm table-striped table-hover table-dark table-bordered">
                    <caption>List of undone homeworks</caption>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Due</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
        
                    <tbody>
                        {% for homework in homeworks %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td class="text-capitalize">{{ homework.title }}</td>
                            <td class="text-capitalize">{{ homework.title }}</td>
                            <td class="text-capitalize">{{ homework.title }}</td>
                            <td>
                                <div class="text-light fw-bold">
                                    NOT DONE
                                </div>
                            </td>
                            <td>
                                <a href="{% url 'homework:delete_homework' homework.id %}">
                                    <i class="fa-solid fa-trash fa-lg"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% else %}
        <h3 class="alert alert-info mt-3">All homeworks appear done</h3>
        {% endif %}
        
        <div class="text-center">
            <a class="btn btn-primary text-center fw-bold p-2" href="{% url 'homework:home' %}">
                Homeworks
            </a>
        </div>
    </div>
    
    
{% endblock content %}
    

dashboard/templates/dashboard/register.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container my-5 d-flex flex-column align-items-center">
        <h3 class="my-3">Create an account</h3>
        <div class="my-3 d-flex-flex-column align-items-center">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-info my-3">Join</button>
            </form>
        <div class="my-3">
            <small class="text-muted fst-italic">Already have an account? <a class="text-decoration-none text-danger" href="{% url 'dashboard:login' %}">Login</a></small>
        </div>
        </div>
    </div>
{% endblock content %}
    