book/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = "book"

urlpatterns = [
    path("", views.home, name="home"),
    path("books/", views.books, name="books"),
    path("books/<int:id>/", views.open_book, name="open_book"),
    path("delete_book/<int:id>/", views.delete_book, name="delete_book"),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("dashboard.urls")),
    path("note/", include("note.urls")),
    path("homework/", include("homework.urls")),
    path("youtube/", include("youtube.urls")),
    path("activity/", include("activity.urls")),
    path("book/", include("book.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("wiki/", include("wiki.urls")),
    path("conversion/", include("conversion.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

book/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User


"""model to hold books saved by the user"""
class Book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    contents = models.FileField(upload_to="books/", validators=[FileExtensionValidator(["pdf", "epub"])])

    def __str__(self):
        """show book title"""
        return self.title

book/forms.py
from django import forms

from .models import Book


"""
create a search youtube form 
fields - texarea
"""
class SearchBookForm(forms.Form):
    text = forms.CharField(max_length=200, label="", required=True,
                                  widget=forms.TextInput(attrs={
                                      "class": "w-100", "placeholder": "book title"
                                  }))


"""form to upload a book"""
class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "contents"]

        labels = {
            "title": "",
            "contents": "(epub or pdf)"
        }

        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control mb-3", "placeholder": "book title"
                }),
        }

book/views.py
import requests

from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import FileResponse
from django.contrib.auth.decorators import login_required

from .forms import SearchBookForm, AddBookForm
from .models import Book


@login_required
def home(request):
    """
    display a search form to search books
    display 10 books searched
    api - https://www.googleapis.com/books/v1/volumes?q={search terms}
    """
    if request.method == "POST":
        form = SearchBookForm(request.POST)

        if form.is_valid():
            text = form.cleaned_data.get("text")

            url = f"https://www.googleapis.com/books/v1/volumes?q={text}"
            response = requests.get(url)
            data = response.json()

            books = []
            for item in data["items"]:
                volume_info = item['volumeInfo']
                book = {
                    'title': volume_info.get('title'),
                    'subtitle': volume_info.get('subtitle'),
                    'description': volume_info.get('description'),
                    'count': volume_info.get('pageCount'),
                    'categories': volume_info.get('categories'),
                    'rating': volume_info.get('averageRating'),
                    'thumbnail': volume_info.get('imageLinks', {}).get('thumbnail'),
                    'preview': volume_info.get('previewLink')
                }

                books.append(book)

            return render(request, "book/home.html", {
                "title": "books",
                "books": books,
                "form": form
            })

    else:
        form = SearchBookForm()

    return render(request, "book/home.html", {
        "title": "books",
        "form": form
    })


@login_required
def books(request):
    """
    add a book to the portal
    display all books
    """

    if request.method == "POST":
        form = AddBookForm(request.POST, request.FILES)

        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get("title")
            contents = form.cleaned_data.get("contents")

            book = Book(user=user, title=title, contents=contents)

            book.save()
            messages.success(request, "New book added")

            return redirect("book:books")
    else:
       form = AddBookForm()

    books_list = Book.objects.filter(user=request.user)
    
    return render(request, "book/books.html", {
        "title": "books",
        "form": form,
        "books": books_list
    })

@login_required
def open_book(request, id):
    """open a book in browser"""
    book = Book.objects.get(user=request.user, id=id)

    if book.contents.name.endswith(".pdf"):
        content_type = "application/pdf"
    elif book.contents.name.endswith(".epub"):
        content_type = "application/epub+zip"
    else:
        raise ValueError("Unsupported file type")

    reading_file = open(book.contents.path, "rb")

    return FileResponse(reading_file, content_type=content_type)

@login_required
def delete_book(request, id):
    """delete a given book by id"""
    book = Book.objects.get(user=request.user, id=id)
    title = book.title
    book.delete()

    messages.info(request, f"'{title.capitalize()}' deleted.")

    return redirect("book:books")

book/templates/book/books.html
{% extends 'dashboard/base.html' %}

{% load crispy_forms_tags %}

{% load static %}


{% block content %}

    
    {% if books %}
        <div class="container mt-4">
            <div class="row">
                
                {% for book in books %}
                    <div class="col-md-2">
                        <div class="card text-center m-3 p-2 shadow">
                            <div class="card-header bg-danger">
                                <h5>{{ book.title }}</h5>
                            </div>
                            <div class="card-body">
                                <a href="{% url 'book:open_book' book.id %}" target="_blank" class="btn btn-warning">
                                    View Book
                                </a>
                            </div>
                            <div class="card-footer bg-info">
                                <a href="{% url 'book:delete_book' book.id %}">
                                    <i class="fa-solid fa-trash fa-lg"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    
                
            </div>
        </div>
    {% else %}
        <div class="alert aler-warning mt-3">No books saved</div>
    {% endif %}
        


    <!-- add book form -->
    <div class="container-sm mt-5 w-50 text-center" style="margin-bottom: 120px;">
        <div class="card">
            <fieldset>
                <legend class="card-title text-success mt-3">
                    <h2 class="fw-bold fs-2">
                        <i class="fa-solid fa-book fa-lg"></i>&nbsp; </i>Add a book
                    </h2>
                </legend>
            </fieldset>
            <form  action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <fieldset class="card-body">
                    {{ form|crispy }}
                </fieldset>
                <fieldset class="card-footer mt-auto">
                    <button class="btn btn-info text-center" type="submit">
                        <i class="fa-solid fa-plus"></i>&nbsp;Add
                    </button>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock content %}
    

book/templates/book/home.html
{% extends 'dashboard/base.html' %}

{% load crispy_forms_tags %}

{% load static %}


{% block content %}

    <!-- redirect to saved books a book -->
    <div class="container-sm">
        <a class="btn btn-success text-decoration-none m-3" href="{% url 'book:books' %}">
            <i class="fa-solid fa-list fa-lg"></i> &nbsp;Saved books
        </a>
    </div>
    


    <!-- Search book form -->
    <div class="container mt-5 text-center" style="margin-bottom: 120px;">
        <div class="card">
            <fieldset>
                <legend class="card-title text-success mt-3">
                    <h2 class="fw-bold fs-2">
                        <i class="fa-solid fa-book fa-lg"></i>&nbsp; </i>Search Books
                    </h2>
                </legend>
            </fieldset>
            <form class="form-group" action="" method="post" autocomplete="off">
                {% csrf_token %}
                <fieldset class="card-body">
                    {{ form|crispy }}
                </fieldset>
                <fieldset class="card-footer mt-auto">
                    <button class="btn btn-outline-warning text-center" type="submit">
                        Search
                    </button>
                </fieldset>
            </form>
        </div>
    </div>


    <!-- Display Search Results -->
    {% if books %}
    <div class="container mt-4">
        <h3 class="text-center text-info">Search Results</h3>
        <div class="row">
            {% for book in books %}
            <div class="col-md-12 mb-4">
                <div class="card m-3 p-3 shadow">
                    <div class="row">
                        <!-- Thumbnail Column -->
                        <div class="col-md-4">
                            {% if book.thumbnail %}
                            <img src="{{ book.thumbnail }}" class="card-img-top img-fluid" alt="{{ book.title }}" style="height: 300px; width: 300px;">
                            {% else %}
                            <img src="{% static 'path/to/placeholder-image.jpg' %}" class="card-img-top img-fluid"
                                alt="{{ book.title }}">
                            {% endif %}
                        </div>
    
                        <!-- Details Column -->
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ book.title }}</h5>
                                {% if book.subtitle %}
                                <h6 class="card-subtitle mb-2 text-muted">{{ book.subtitle }}</h6>
                                {% endif %}
                                <p class="card-text">{{ book.description|truncatewords:40 }}</p>
                                <h4 class="card-text"><strong>Categories:</strong> </h4>
                                    {% if book.categories %}
                                        {% for category in book.categories %}
                                           <p>{{ category }}</p>
                                        {% endfor %}
                                    {% else %}
                                        <p>Not defined</p>    
                                    {% endif %}
                                <p class="card-text"><strong>Pages:</strong> {{ book.count|default:"N/A" }}</p>
                                <p class="card-text"><strong>Rating:</strong> {{ book.rating|default:"N/A" }}</p>
                                <a href="{{ book.preview }}" class="btn btn-primary" target="_blank">Preview</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}


{% endblock content %}
    