activity/urls.py
from django.urls import path

from . import views


app_name = "activity"

urlpatterns = [
    path("", views.home, name="home"),
    path("update_activity/<int:id>/", views.update_activity, name="update_activity"),
    path("delete_activity/<int:id>/", views.delete_activity, name="delete_activity"),
]

book/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = "book"

urlpatterns = [
    path("", views.home, name="home"),
    path("books/", views.books, name="books"),
    path("books/<int:id>/", views.open_book, name="open_book"),
    path("delete_book/<int:id>/", views.delete_book, name="delete_book"),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views


app_name = "dashboard"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register, name="register"),
    
    path("profile/", views.profile, name="profile"),
    path("signout/", views.signout, name="signout")
]

note/urls.py
from django.urls import path

from . import views


app_name = "note"

urlpatterns = [
    path("", views.home, name="home"),
    path("note-detail/<int:id>/", views.note_detail, name="note_detail"),
    path("note-delete/<int:id>/", views.note_delete, name="note_delete"),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("dashboard.urls")),
    path("note/", include("note.urls")),
    path("homework/", include("homework.urls")),
    path("youtube/", include("youtube.urls")),
    path("activity/", include("activity.urls")),
    path("book/", include("book.urls")),
    path("dictionary/", include("dictionary.urls")),
    path("wiki/", include("wiki.urls")),
    path("conversion/", include("conversion.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wiki/urls.py
from django.urls import path

from . import views


app_name = "wiki"

urlpatterns = [
    path("", views.home, name="home"),
]

youtube/urls.py
from django.urls import path

from . import views


app_name = "youtube"

urlpatterns = [
    path("", views.home, name="home"),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        
class ChangeUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]
        

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from activity.models import Activity
from homework.models import Homework

from .forms import RegisterUserForm, ChangeUserForm


def home(request):

    return render(request, "dashboard/home.html", {"title": "dashboard"})

def login_user(request):
    if request.method == "POST":
        data = request.POST
        username = data["username"]
        password = data["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, "Logged in...")
            return redirect("dashboard:home")
            
        else:
            messages.warning(request, "Invalid details...")
            return redirect(request.path)
    
    return render(request, "dashboard/login.html", {"title": "login"})

def register(request):
    if request.user.is_authenticated:
        return redirect("dashboard:home")
    form = RegisterUserForm()
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            data = form.cleaned_data
            username = data["username"]
            password = data["password1"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, "User created and logged in...")
                return redirect("dashboard:home")
        else:
            for error in list(form.errors.value()):
                messages.warning(request, error)
            return redirect(request.path)
    
    context = {
        "title": "register",
        "form": form,
    }
    
    return render(request, "dashboard/register.html", context)

@login_required
def profile(request):
    """
    return undone activities
    return undone homeworks
    """
    activities = Activity.objects.filter(user=request.user, is_finished=False)
    homeworks = Homework.objects.filter(user=request.user, is_finished=False)

    return render(request, "dashboard/profile.html", {
        "activities": activities,
        "homeworks": homeworks,
        "title": "profile"
    })

@login_required
def signout(request):
    """
    logout the current user
    """
    logout(request)

    return redirect("dashboard:home")

dashboard/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar bg-secondary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dashboard:home' %}">
            Study Portal &nbsp;<i class="fa-solid fa-building-columns fa-lg"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02"
            aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'dashboard:home' %}">Home</a>
                </li>
                
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Options
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'note:home' %}">Notes</a></li>
                            <li><a class="dropdown-item" href="{% url 'homework:home' %}">Homework</a></li>
                            <li><a class="dropdown-item" href="{% url 'youtube:home' %}">Youtube</a></li>
                            <li><a class="dropdown-item" href="{% url 'activity:home' %}">Activities</a></li>
                            <li><a class="dropdown-item" href="{% url 'book:home' %}">Books</a></li>
                            <li><a class="dropdown-item" href="{% url 'dictionary:home' %}">Dictionary</a></li>
                            <li><a class="dropdown-item" href="{% url 'wiki:home' %}">Wikipedia</a></li>
                            <li><a class="dropdown-item" href="{% url 'conversion:index' %}">Conversion</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-primary" href="{% url 'dashboard:signout' %}">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-success" href="{% url 'dashboard:login' %}">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-success" href="{% url 'dashboard:register' %}">Join</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>